# Generated by Django 4.1.2 on 2022-10-26 21:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog_portal', '0002_articleobjects_category_article_status_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ArticleObjects',
        ),
        migrations.RemoveField(
            model_name='article',
            name='category',
        ),
        migrations.RemoveField(
            model_name='article',
            name='status',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
