# Generated by Django 4.1.2 on 2022-11-27 11:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Panel', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
